name: Feature workflow

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: read
  checks: write

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  unittests:
    uses: ./.github/workflows/run-unittests.yml
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]'
