jobs:
  unittests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .python-version and ${{ matrix.python-version }}
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: 3.7.17
          versions: ${{ matrix.python-version }}

      - name: Switch to .python-version
        run: |
          pyenv local "$(cat .python-version)"
          if python -V | grep -q "$(cat .python-version)"; then
            echo "Python version is '$(python -V)'"
          else
            echo "Python version is '$(python -V)', but should be '$(cat .python-version)'. Exiting workflow."
            exit 1
          fi

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Setup virtual environment
        run: |
          pipenv --python ${{ matrix.python-version }} install --dev --deploy

      - name: Verify virtual environment uses python version ${{ matrix.python-version }}
        run: |
          if pipenv run python -V | grep -q "${{ matrix.python-version }}"; then
            echo "Python ${{ matrix.python-version }} is being used."
          else
            echo "Python ${{ matrix.python-version }} is not being used. Exiting workflow."
            exit 1
          fi

      - name: Run unittests
        run: |
          PYTHONPATH=./src:./tests pipenv run pytest ./tests
